packages:
   - "./@apps/**"
   - "./packages/**"

catalog:
   bootstrap: "^5.3.3"
   i18next: "^24.2.0"
   i18next-http-backend: "^3.0.1"
   i18next-vue: "^5.0.0"
   pinia: "^2.3.0"
   vue: "^3.5.13"
   vue-router: "^4.5.0"
